### ISSUE TITLE
关于推理测试过程中缺少参数的问题？

### ISSUE THREAD

**Issue by cenchaojun** [dawn-ech/YOLC#5]
Traceback (most recent call last):
  File "/data3/testdata/ccj/code/YOLC/test_ob.py", line 288, in <module>
    main()
  File "/data3/testdata/ccj/code/YOLC/test_ob.py", line 244, in main
    outputs = single_gpu_test(model, data_loader, args.show, args.show_dir,
  File "/data3/testdata/ccj/code/YOLC/mmdetection/mmdet/apis/test.py", line 49, in single_gpu_test
    out_file = osp.join(out_dir, img_meta['ori_filename'])
KeyError: 'ori_filename'

您好，在进行推理的时候发现出现这样一个错误，请问这是什么原因呢。

**Comment by dawn-ech** [comment]
应该是[https://github.com/open-mmlab/mmdetection/issues/7842](这个问题)，测试时参数只用--eval bbox，不需要其他参数可以正常推理
