### ISSUE TITLE
FileNotFoundError: VisDroneDataset: [Errno 2] No such file or directory: 'Offshore-platform'

### ISSUE THREAD

**Issue by QMLmulan** [dawn-ech/YOLC#8]
作者您好，我想请问一下，我在"D:\xxx\YOLC-main\configs\yolc.py"中，classes = ("Offshore-platform")替换了自己的类，还是出现这样
FileNotFoundError: VisDroneDataset: [Errno 2] No such file or directory: 'Offshore-platform'，请问还有哪里需要再修改？D:\xxx\YOLC-main\VisDrone_Dataset.py里的CLASSES = (‘’Offshore-platform，'bicycle', 'car', 'motorcycle', 'airplane', 'bus',~)我也对应加了，不知道还有哪里需要修改，求助求助

**Comment by dawn-ech** [comment]
可以贴一下完整的报错吗，以及配置文件

**Comment by QMLmulan** [comment]
Traceback (most recent call last):
&nbsp; File "train.py", line 250, in <module&gt;
&nbsp; &nbsp; main()
&nbsp; File "train.py", line 239, in main
&nbsp; &nbsp; train_detector(
&nbsp; File "C:\Users\nsd\.conda\envs\yolo\lib\site-packages\mmdet\apis\train.py", line 246, in train_detector
&nbsp; &nbsp; runner.run(data_loaders, cfg.workflow)
&nbsp; File "C:\Users\nsd\.conda\envs\yolo\lib\site-packages\mmcv\runner\epoch_based_runner.py", line 127, in run&nbsp; &nbsp; &nbsp; &nbsp;
&nbsp; &nbsp; epoch_runner(data_loaders[i], **kwargs)
&nbsp; File "C:\Users\nsd\.conda\envs\yolo\lib\site-packages\mmcv\runner\epoch_based_runner.py", line 47, in train&nbsp; &nbsp; &nbsp;&nbsp;
&nbsp; &nbsp; for i, data_batch in enumerate(self.data_loader):
&nbsp; File "C:\Users\nsd\.conda\envs\yolo\lib\site-packages\torch\utils\data\dataloader.py", line 355, in __iter__&nbsp; &nbsp; &nbsp;
&nbsp; &nbsp; return self._get_iterator()
&nbsp; File "C:\Users\nsd\.conda\envs\yolo\lib\site-packages\torch\utils\data\dataloader.py", line 301, in _get_iterator
&nbsp; &nbsp; return _MultiProcessingDataLoaderIter(self)
&nbsp; File "C:\Users\nsd\.conda\envs\yolo\lib\site-packages\torch\utils\data\dataloader.py", line 940, in __init__
&nbsp; &nbsp; self._reset(loader, first_iter=True)
&nbsp; File "C:\Users\nsd\.conda\envs\yolo\lib\site-packages\torch\utils\data\dataloader.py", line 971, in _reset
&nbsp; &nbsp; self._try_put_index()
&nbsp; File "C:\Users\nsd\.conda\envs\yolo\lib\site-packages\torch\utils\data\dataloader.py", line 1205, in _try_put_index
&nbsp; &nbsp; index = self._next_index()
&nbsp; File "C:\Users\nsd\.conda\envs\yolo\lib\site-packages\torch\utils\data\dataloader.py", line 508, in _next_index
&nbsp; &nbsp; return next(self._sampler_iter)&nbsp; # may raise StopIteration
&nbsp; File "C:\Users\nsd\.conda\envs\yolo\lib\site-packages\torch\utils\data\sampler.py", line 227, in __iter__
&nbsp; &nbsp; for idx in self.sampler:
&nbsp; File "C:\Users\nsd\.conda\envs\yolo\lib\site-packages\mmdet\datasets\samplers\group_sampler.py", line 36, in __iter__
&nbsp; &nbsp; indices = np.concatenate(indices)
&nbsp; File "<__array_function__ internals&gt;", line 180, in concatenate
ValueError: need at least one array to concatenate





------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年8月30日(星期五) 下午5:25
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [dawn-ech/YOLC] FileNotFoundError: VisDroneDataset: [Errno 2] No such file or directory: &#39;Offshore-platform&#39; (Issue #8)














 
可以贴一下完整的报错吗，以及配置文件

**Comment by dawn-ech** [comment]
从报错看不出来问题在哪。可以先检查下config里的文件路径是否正确，只改classes和文件路径应该没问题

**Comment by yjyj2000** [comment]
@QMLmulan 我遇到了相同的问题，请问你是怎么解决的？我训练自己的数据集也是这样

**Comment by QMLmulan** [comment]
已收到您的邮件，我会尽快给你回复。谢谢

**Comment by QMLmulan** [comment]
好像是划分数据集的时候有点问题，你对照一下他的数据标签




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年11月24日(星期天) 中午12:19
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [dawn-ech/YOLC] FileNotFoundError: VisDroneDataset: [Errno 2] No such file or directory: &#39;Offshore-platform&#39; (Issue #8)














 
@QMLmulan 我遇到了相同的问题，请问你是怎么解决的？我训练自己的数据集也是这样

**Comment by yjyj2000** [comment]
> 好像是划分数据集的时候有点问题，你对照一下他的数据标签
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2024年11月24日(星期天) 中午12:19 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [dawn-ech/YOLC] FileNotFoundError: VisDroneDataset: [Errno 2] No such file or directory: &#39;Offshore-platform&#39; (Issue #8) @QMLmulan 我遇到了相同的问题，请问你是怎么解决的？我训练自己的数据集也是这样 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

好的，谢谢
